### ISSUE TITLE
Low Voltages (out of standard eurorack scaling) from Satonaut

### ISSUE THREAD

**Issue by mjsyts** [clone45/voxglitch#176] opened 2022-09-12 21:29 UTC
<img width="509" alt="Screen Shot 2022-09-12 at 5 26 30 PM" src="https://user-images.githubusercontent.com/77947318/189761758-2b4f52d6-49bf-4643-9dcf-af65f3bf2d6d.png">

Just got the update - some combination of these modules (AFAIK this is mostly related to the Satonaut) are outputting EXTREMELY low values - in the range of (-10) - (-500) volts.

**Comment by clone45** [comment] 2022-09-12 21:34
Hello!  Thanks for submitting this bug.  My apologies for the inconvenience.  Can you tell me if you're on Windows or Mac?  Also, does the Drive knob on the Satanonaut make any difference?  Thanks!

**Comment by mjsyts** [comment] 2022-09-12 21:41
I'm on a Mac. Drive knob seems unrelated. Setting any of the other knobs still results in very low voltages

**Comment by mjsyts** [comment] 2022-09-12 21:42
But those panels look glorious 👍

**Comment by clone45** [comment] 2022-09-12 21:53
Ha ha ha!  Thank you!

I think that I know that the issue is, but it's going to take me a little bit of time to fix.  I ran into a similar issue recently where I forgot to initialize an array with values.  This hadn't caused me issues in the past, but recently I got error reports from Mac users that the delay used in the Groovebox was causing a similar issue.  I fixed that one, but I haven't fixed the buffers used in Satanonaut yet.  That's probably what's wrong.

I'll get this fixed ASAP.  It should be fixed in version 2.21.3

**Comment by mjsyts** [comment] 2022-09-12 22:03
Oof. Done that before and I would bet this is exactly the issue as well though I haven't done too much looking through it. Is that in the Satonaut header? I'm guessing that's where the problem is, not that you wouldn't probably already know.

**Comment by clone45** [comment] 2022-09-12 22:12
It's in /src/Satanonaut/SatanonautAudioBuffer.hpp and SatanonautStereoAudioBuffer.hpp  :-)  I'm about to submit the fix to the library.   :-)

**Closed** 2022-09-24 22:53 UTC
